# Generated by Django 5.1 on 2024-08-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("image_time", models.DateTimeField(blank=True, null=True)),
                ("image_id", models.CharField(blank=True, max_length=255, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploaded_images/"
                    ),
                ),
            ],
        ),
    ]
