# Generated by Django 5.1 on 2024-08-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildata",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
