# Generated by Django 5.1 on 2024-09-18 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaildata",
            name="show_image",
        ),
        migrations.RemoveField(
            model_name="emaildata",
            name="show_map",
        ),
    ]
