# Generated by Django 5.1 on 2024-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_remove_emaildata_show_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildata",
            name="show_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emaildata",
            name="show_map",
            field=models.BooleanField(default=False),
        ),
    ]
