# Generated by Django 5.1 on 2024-08-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0002_alter_emaildata_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildata",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="emaildata",
            name="image_file",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
