# Generated by Django 5.1 on 2024-09-18 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0003_emaildata_show_image_emaildata_show_map"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaildata",
            name="show_image",
        ),
        migrations.RemoveField(
            model_name="emaildata",
            name="show_map",
        ),
    ]
