# Generated by Django 5.1 on 2024-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0004_alter_emaildata_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildata",
            name="status",
            field=models.CharField(default="Nuovo", max_length=50),
        ),
    ]
