# Generated by Django 5.1 on 2025-07-31 19:20

import emails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_emaildata_show_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='image_file',
            field=emails.fields.RemoteImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='typo',
            field=models.CharField(choices=[('waste', 'Rifiuti'), ('notrunktree', 'Tronchi'), ('tree', 'Censimento'), ('pianta', 'Piantumazione'), ('hole', 'Buche'), ('api', 'API'), ('rimuovi', 'Rimuovi')], default='rifiuti', max_length=20),
        ),
    ]
