# Generated by Django 5.1 on 2024-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0005_emaildata_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildata",
            name="typo",
            field=models.CharField(
                choices=[
                    ("rifiuti", "Rifiuti"),
                    ("alberi", "Alberi Abbattuti"),
                    ("buche", "Buche"),
                ],
                default="rifiuti",
                max_length=20,
            ),
        ),
    ]
