# Generated by Django 5.1 on 2025-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_emaildata_image_file_alter_emaildata_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='typo',
            field=models.CharField(choices=[('waste', 'Rifiuti'), ('notrunktree', 'Tronchi'), ('tree', 'Censimento'), ('pianta', 'Piantumazione'), ('cantieri', 'Cantieri-Interventi'), ('hole', 'Buche'), ('api', 'API'), ('rimuovi', 'Rimuovi')], default='rifiuti', max_length=20),
        ),
    ]
