# Generated by Django 5.1 on 2026-02-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_alter_emaildata_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
