# Generated by Django 5.1 on 2024-09-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_emaildata_typo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildata",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="emaildata",
            name="typo",
            field=models.CharField(
                choices=[
                    ("waste", "Rifiuti"),
                    ("notrunktree", "Tronchi"),
                    ("tree", "Censimento alberi "),
                    ("hole", "Buche"),
                ],
                default="rifiuti",
                max_length=20,
            ),
        ),
    ]
