# Generated by Django 5.1 on 2026-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_alter_emaildata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
