# Generated by Django 5.1 on 2026-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_alter_emaildata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
