# Generated by Django 5.1 on 2026-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_alter_emaildata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
