# Generated by Django 5.1 on 2026-05-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_alter_emaildata_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='status_int',
            field=models.IntegerField(blank=True, choices=[(0, 'Nuovo'), (10, 'In elaborazione'), (20, 'Geolocalizzato'), (30, 'Completato'), (40, 'Duplicato'), (50, 'Errore'), (60, 'Saltato'), (70, 'In attesa di revisione')], db_index=True, null=True),
        ),
    ]
