# Generated by Django 5.1 on 2026-05-07 07:00
# in migrations/xxxx_auto_populate_status_int.py
from django.db import migrations

def map_old_status_to_int(old_status):
    """Converte i vecchi valori testuali nei codici interi"""
    mapping = {
        'nuovo': 0, 'new': 0,
        'in elaborazione': 10, 'processing': 10,
        'in_elaborazione': 10,
        'geolocalizzato': 20, 'geocoded': 20,
        'completato': 30, 'completed': 30,
        'duplicato': 40, 'duplicate': 40,
        'errore': 50, 'error': 50,
        'saltato': 60, 'skipped': 60,
        'in attesa di revisione': 70, 'pending_review': 70,
        'in attesa': 70,
    }
    key = old_status.lower().strip()
    return mapping.get(key, 50)   # default a ERROR (50)

def populate_status_int(apps, schema_editor):
    EmailData = apps.get_model('emails', 'EmailData')
    for obj in EmailData.objects.all():
        obj.status_int = map_old_status_to_int(obj.status)
        obj.save(update_fields=['status_int'])

class Migration(migrations.Migration):
    dependencies = [('emails', '0012_emaildata_status_int')]
    operations = [
        migrations.RunPython(populate_status_int),
    ]
