# Generated by Django 5.1 on 2026-05-07 08:15
# migrations/0015_clean_duplicate_image_id.py
from django.db import migrations, models

def deduplicate_image_id(apps, schema_editor):
    EmailData = apps.get_model('emails', 'EmailData')
    # Trova gli image_id con conteggio >1
    dup_ids = (
        EmailData.objects.values('image_id')
        .annotate(cnt=models.Count('id'))
        .filter(cnt__gt=1)
    )
    for group in dup_ids:
        image_id = group['image_id']
        records = EmailData.objects.filter(image_id=image_id).order_by('id')
        # Decide quale tenere: ad esempio quello con status non ERROR, o con immagine valida
        best = None
        for rec in records:
            # Priorità: record con image_url non vuoto e status non DUPLICATE/ERROR
            if rec.image_url and rec.status_int not in (50, 40):
                best = rec
                break
        if not best:
            best = records.first()  # tiene il più vecchio
        # Elimina tutti tranne il migliore
        to_delete = records.exclude(id=best.id)
        to_delete.delete()
        print(f"Mantenuto ID {best.id} per image_id {image_id}, eliminati {to_delete.count()}")

class Migration(migrations.Migration):
    dependencies = [('emails', '0013_auto_20260507_0700')]  # la tua ultima migrazione
    #dependencies = [('emails', '0014_fix_status_int')]  # la tua ultima migrazione
    operations = [
        migrations.RunPython(deduplicate_image_id),
    ]
