# Generated by Django 5.1 on 2026-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_auto_20260507_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
