# Generated by Django 5.1 on 2026-05-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0015_alter_emaildata_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
