# Generated by Django 5.1 on 2026-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0016_alter_emaildata_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='emaildata',
            name='quartiere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
