# Generated by Django 5.1 on 2026-07-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0017_users_emaildata_quartiere'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
