# Generated by Django 5.1 on 2026-07-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0018_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='status_int',
            field=models.IntegerField(blank=True, choices=[(0, 'Nuovo'), (10, 'In elaborazione'), (20, 'Pubblicata'), (30, 'Rifiutata'), (40, 'Segnalata per revisione')], db_index=True, null=True),
        ),
    ]
