# Generated by Django 5.1 on 2026-09-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0019_alter_emaildata_status_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.CharField(choices=[('face', 'Volto'), ('plate', 'Targa')], max_length=10)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('confidence', models.FloatField(default=1.0)),
                ('confirmed', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='emails.emaildata')),
            ],
        ),
    ]
