# Generated by Django 5.1 on 2026-09-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0020_redactionbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='redacted_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
