# Generated by Django 5.1 on 2026-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0021_emaildata_redacted_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='latitude_float',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='longitude_float',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
