"""
Django settings for GeoDumbMail project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import certifi, os
import logging

from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-js8_#xdhrvdavxja3e$7copz#$%p1p1=&w5i(srsnvyguv03*8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://ws.citylog.cloud',
    'https://citylog.cloud',  # Assicurati di aggiungere anche il tuo dominio.
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'emails',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "GeoDumbMail.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates'),],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "emails.context_processors.imap_server_info",
            ],
        },
    },
]

WSGI_APPLICATION = "GeoDumbMail.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": BASE_DIR / "db.sqlite3",
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', 	# Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'geodumbmail_alembic',                          # Or path to database file if using sqlite3.
        #'NAME': 'geodumbmail',                                 # Or path to database file if using sqlite3.
        'USER': 'postgres',                                     # Not used with sqlite3.
        'PASSWORD':'postgres',                                  # Not used with sqlite3.
        'HOST': '192.168.1.65',                                 # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '5432',                                         # Set to empty string for default. Not used with sqlite3.
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Carica le variabili dal file .env
load_dotenv(BASE_DIR / '.env')

EMAIL_BACKEND = 'emails.email_backend.CustomEmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'mail.citylog.cloud'
#EMAIL_HOST = 'vps-e993bee2.vps.ovh.net'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

# Configura il contesto SSL ignorando la verifica per i test
#ssl_context = ssl.create_default_context()
#ssl_context.check_hostname = False
#ssl_context.verify_mode = ssl.CERT_NONE

#os.environ['SSL_CERT_FILE'] = certifi.where()
#os.environ['SSL_CERT_FILE'] = '/etc/ssl/certs/cacert.pem'

# Notifica del server IMAP in uso mail.citylog.cloud o vps-e993bee2.vps.ovh.net
# nell'area alert-box del backend
SERVER_IMAP = 'mail.citylog.cloud'
#SERVER_IMAP = 'vps-e993bee2.vps.ovh.net' # original
MAIL_TO_GET_REPORT = 'report@citylog.cloud'
PWD_TO_GET_REPORT = os.environ.get('PWD_TO_GET_REPORT')
#PWD_TO_GET_REPORT = 'Blacking1'          # original

# Notifica del server IMAP in uso mail.citylog.cloud o vps-e993bee2.vps.ovh.net
# nell'area alert-box del backend
#IMAP_HOST = "mail.citylog.cloud"
IMAP_PROVIDER_NAME = "Zimbra primario"
IMAP_SERVER_LABEL = f"{IMAP_PROVIDER_NAME} ({SERVER_IMAP})"

EMAIL_USE_SSL = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'emails': {  # nome della tua app
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# Package that stores remotly images to servers as > ws | ws1 | ws2
DEFAULT_FILE_STORAGE = "custom_storage.backends.CustomRemoteStorage"

# Parametri configurabili originali per il backend ufficiale immagini remote - proxmox
#REMOTE_STORAGE_UPLOAD_URL = 'https://ws.citylog.cloud/upload'
#REMOTE_STORAGE_MEDIA_URL = 'https://ws.citylog.cloud/media'
#REMOTE_STORAGE_DELETE_URL = "https://ws.citylog.cloud/delete"

# --- Remote Storage Server Selection ---
# Cambia REMOTE_STORAGE_ACTIVE_SERVER per shiftare tra i container
# 'primary'   → ws.citylog.cloud  (proxmox - in manutenzione)
# 'secondary' → ws2.citylog.cloud (fallback attivoi openvz)

# Gestione di multipli server storage remoti per le immagini
REMOTE_STORAGE_ACTIVE_SERVER = 'primary'

_REMOTE_STORAGE_SERVERS = {
    'primary': {
        # proxmox - originale, ripristinare quando torna disponibile
        'UPLOAD_URL': 'https://ws.citylog.cloud/upload',
        'MEDIA_URL':  'https://ws.citylog.cloud/media',
        'DELETE_URL': 'https://ws.citylog.cloud/delete',
    },
    'secondary': {
        # fallback attivo durante manutenzione ws
        'UPLOAD_URL': 'https://ws2.citylog.cloud/upload',
        'MEDIA_URL':  'https://ws2.citylog.cloud/media',
        'DELETE_URL': 'https://ws2.citylog.cloud/delete',
    },
    'thernary': {
        # fallback attivo durante manutenzione ws
        'UPLOAD_URL': 'https://ws3.citylog.cloud/upload',
        'MEDIA_URL':  'https://ws3.citylog.cloud/media',
        'DELETE_URL': 'https://ws3.citylog.cloud/delete',
    },
}

_active = _REMOTE_STORAGE_SERVERS[REMOTE_STORAGE_ACTIVE_SERVER]
REMOTE_STORAGE_UPLOAD_URL = _active['UPLOAD_URL']
REMOTE_STORAGE_MEDIA_URL  = _active['MEDIA_URL']
REMOTE_STORAGE_DELETE_URL = _active['DELETE_URL']

# Server per accedere agli endpoint FastAPI - uficiale api2.citylog.cloud
FASTAPI_BASE_URL = "https://api2.citylog.cloud/"
#SERVICE_FACEBOOK_ID = "marco@example.com"
#SERVICE_EMAIL = "marco@example.com"

### ANTROPIC SETUP
from dotenv import load_dotenv

#load_dotenv()  # legge .env e popola os.environ
load_dotenv(BASE_DIR / '.env')

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY')

if not ANTHROPIC_API_KEY:
    raise RuntimeError(
        "ANTHROPIC_API_KEY non trovata: assicurati di avere un file .env "
        "nella root del progetto con la chiave impostata."
    )

# API LLM di Claude in uso
#DETECTION_MODEL = os.environ.get('DETECTION_MODEL', 'claude-sonnet-4-6')
DETECTION_MODEL = os.environ.get('DETECTION_MODEL', 'claude-haiku-4-5-20251001')
# Abilita l'attivazione dell'API ANTROPIC
ENABLE_ANTROPIC = True

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
